#!/bin/bash

if [ -z ${ZEPHYR_BASE} ]; then
    echo "Run 'source zephyr-env.sh' first"
    exit 1
fi

docker run \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/shadow:/etc/shadow:ro \
    -v /etc/group:/etc/group:ro \
    -v /usr/lib/locale:/usr/lib/locale:ro \
    -v ${HOME}/.bash_history:${HOME}/.bash_history \
    -v ${ZEPHYR_BASE}:${ZEPHYR_BASE} \
    -e LANG=C.UTF-8 \
    -e LC_ALL=C.UTF-8 \
    -e TZ=$(cat /etc/timezone) \
    -e ZEPHYR_BASE=${ZEPHYR_BASE} \
    -e ZEPHYR_GCC_VARIANT=gccarmemb \
    -e GCCARMEMB_TOOLCHAIN_PATH=/usr \
    -e CROSS_COMPILE=/usr/bin/arm-none-eabi- \
    --privileged \
    --group-add=plugdev \
    -w ${PWD} \
    -u $(id -u):$(id -g) \
    --rm \
    -it \
    agustinhenze/zephyr-arm bash
